// This file is generated by vinext. Do not edit.
import type * as React from "react";

declare global {
  type PageProps<Route extends VinextRouteTypes.PageRoute = VinextRouteTypes.PageRoute> = {
    params: Promise<VinextRouteTypes.ParamMap[Route]>;
    searchParams: Promise<Record<string, string | string[] | undefined>>;
  };

  type LayoutProps<Route extends VinextRouteTypes.LayoutRoute> = {
    params: Promise<VinextRouteTypes.ParamMap[Route]>;
    children: React.ReactNode;
  } & {
    [K in VinextRouteTypes.LayoutSlotMap[Route]]: React.ReactNode;
  };

  type RouteContext<Route extends VinextRouteTypes.RouteHandlerRoute = VinextRouteTypes.RouteHandlerRoute> = {
    params: Promise<VinextRouteTypes.ParamMap[Route]>;
  };
}

declare namespace VinextRouteTypes {
  type PageRoute = "/" | "/dashboard" | "/profile";
  type LayoutRoute = "/";
  type RouteHandlerRoute = "/api/coach" | "/api/converse" | "/api/email-unsubscribe" | "/api/email-verify" | "/api/evaluate" | "/api/feedback" | "/api/library" | "/api/lifeline" | "/api/moment-review" | "/api/moments" | "/api/pronunciation" | "/api/realtime-token" | "/api/rescue" | "/api/retrieval" | "/api/retrieval-email" | "/api/transcribe" | "/api/variation" | "/api/word-bank";
  type AppRoute = "/" | "/api/coach" | "/api/converse" | "/api/email-unsubscribe" | "/api/email-verify" | "/api/evaluate" | "/api/feedback" | "/api/library" | "/api/lifeline" | "/api/moment-review" | "/api/moments" | "/api/pronunciation" | "/api/realtime-token" | "/api/rescue" | "/api/retrieval" | "/api/retrieval-email" | "/api/transcribe" | "/api/variation" | "/api/word-bank" | "/dashboard" | "/profile";

  interface ParamMap {
    "/": {};
    "/api/coach": {};
    "/api/converse": {};
    "/api/email-unsubscribe": {};
    "/api/email-verify": {};
    "/api/evaluate": {};
    "/api/feedback": {};
    "/api/library": {};
    "/api/lifeline": {};
    "/api/moment-review": {};
    "/api/moments": {};
    "/api/pronunciation": {};
    "/api/realtime-token": {};
    "/api/rescue": {};
    "/api/retrieval": {};
    "/api/retrieval-email": {};
    "/api/transcribe": {};
    "/api/variation": {};
    "/api/word-bank": {};
    "/dashboard": {};
    "/profile": {};
  }

  interface LayoutSlotMap {
    "/": never;
  }
}



export {};
